export const DEFAULT_SERVICES = [
  { idService: 1, nomService: "Cellule informatique", description: "Cellule informatique", etage: "2eme" },
  { idService: 2, nomService: "Bureau d'ordre", description: "Greffe", etage: "1er" },
  { idService: 3, nomService: "Ouverture des dossiers", description: "Ouverture des dossiers", etage: "RDC" },
  { idService: 4, nomService: "Distribution", description: "Distribution", etage: "2eme" },
  { idService: 5, nomService: "Chef de service", description: "Chef de service", etage: "2eme" },
  { idService: 6, nomService: "Admin systeme", description: "Admin systeme", etage: "2eme" },
  { idService: 7, nomService: "Notification et remise des copies", description: "Notification et remise des copies", etage: "1er" },
  { idService: 8, nomService: "Expertise", description: "Expertise", etage: "1er" },
  { idService: 9, nomService: "Cassation", description: "Cassation", etage: "2eme" },
  { idService: 10, nomService: "Remise des copies (fusionne)", description: "Service fusionne avec Notification", etage: "RDC" },
  { idService: 11, nomService: "Secretariat particulier", description: "Secretariat particulier", etage: "2eme" },
  { idService: 13, nomService: "Archivage", description: "Archivage", etage: "Sous-sol" },
  { idService: 15, nomService: "Conseiller rapporteur", description: "Conseiller rapporteur", etage: "2eme" },
  { idService: 16, nomService: "Refere", description: "Refere", etage: "1er" },
  { idService: 17, nomService: "Jugement au fond", description: "Jugement au fond", etage: "2eme" },
  { idService: 18, nomService: "Commissaire royal", description: "Commissaire royal", etage: "2eme" },
  { idService: 19, nomService: "Premier president", description: "Premier president", etage: "3eme" },
  { idService: 20, nomService: "Gestion de retrait", description: "Gestion de retrait", etage: "1er" },
  { idService: 21, nomService: "إجراءات و جلسات الثلاثاء", description: "Procedures et audiences mardi", etage: "1er" },
  { idService: 22, nomService: "إجراءات و جلسات الخميس", description: "Procedures et audiences Jeudi", etage: "1er" },
];
