export const DEFAULT_SERVICES = [
  { idService: 1, nomService: "خلية المعلوميات", description: "Cellule informatique", etage: "2ème" },
  { idService: 2, nomService: "مكتب الضبط", description: "Greffe", etage: "1er" },
  { idService: 3, nomService: "فتح الملفات", description: "Ouverture des dossiers", etage: "RDC" },
  { idService: 4, nomService: "التوزيع", description: "Distribution", etage: "2ème" },
  { idService: 5, nomService: "رئيس المصلحة", description: "Chef de service", etage: "2ème" },
  { idService: 6, nomService: "مدير النظام", description: "Admin système", etage: "2ème" },
  { idService: 7, nomService: "التبليغ", description: "Notification", etage: "1er" },
  { idService: 8, nomService: "خبرة", description: "Expertise", etage: "1er" },
  { idService: 9, nomService: "النقض", description: "Cassation", etage: "2ème" },
  { idService: 10, nomService: "تسليم النسخ", description: "Remise des copies", etage: "RDC" },
  { idService: 11, nomService: "الكتابة الخاصة", description: "Secrétariat particulier", etage: "2ème" },
  { idService: 12, nomService: "الجلسات", description: "Audiences", etage: "1er" },
  { idService: 13, nomService: "الحفظ", description: "Archivage", etage: "Sous-sol" },
  { idService: 14, nomService: "الإجراءات", description: "Procédures", etage: "1er" },
  { idService: 15, nomService: "المستشار المقرر", description: "Conseiller rapporteur", etage: "2ème" },
  { idService: 16, nomService: "الاستعجالي", description: "Référé", etage: "1er" },
  { idService: 17, nomService: "قضاء الموضوع", description: "Jugement au fond", etage: "2ème" },
  { idService: 18, nomService: "المفوض الملكي", description: "Commissaire royal", etage: "2ème" },
  { idService: 19, nomService: "الرئيس الأول", description: "Premier président", etage: "3ème" },
  { idService: 20, nomService: "تدبير السحب", description: "Gestion de retrait", etage: "1er" },
];
